# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SurveyTimeRange(BaseModel):
    since: datetime = Field(..., title="Since")
    until: datetime = Field(..., title="Until")
    timezone: Optional[TimezoneInfo] = Field(
        default_factory=lambda: TimezoneInfo.model_validate(
            {"label": "UTC", "tzCode": "UTC", "name": "UTC", "utc": "+00:00"}
        ),
        title="Timezone",
    )
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class GeeClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class PatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class EarthRangerConfig(BaseModel):
    server: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )
    patrol_type_id: str = Field(
        ...,
        description="Numeric or UUID identifier for the patrol type in EarthRanger.",
        title="Patrol Type ID",
    )


class SurveyConfig(BaseModel):
    surveyName: str = Field(
        ...,
        description="A unique name identifying this survey (e.g. 'Amboseli Elephant Survey Q1 2026').",
        title="Survey Name",
    )
    time_range: SurveyTimeRange = Field(
        ...,
        description="The date/time window covered by this survey.",
        title="Time Range",
    )
    erSpatialTransectsGroupId: str = Field(
        ...,
        description="EarthRanger spatial group ID that contains the transect features.",
        title="Transects Group ID",
    )


class ConnectionConfigEntry(BaseModel):
    earthranger: EarthRangerConfig = Field(..., title="")
    surveys: List[SurveyConfig] = Field(..., title="Surveys")


class ConnectionConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entries: List[ConnectionConfigEntry] = Field(..., title="Entries")


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    gee_client: Optional[GeeClient] = Field(
        None, title="Configure Google Earth Engine connection"
    )
    connection_config: Optional[ConnectionConfig] = Field(
        None, title="Configure EarthRanger connection"
    )
    patrol_traj: Optional[PatrolTraj] = Field(None, title="Trajectory segment filter")
