# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Dsc Analysis
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_big_life.tasks import filter_numeric_df as filter_numeric_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_constant_column as add_constant_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_off_transect_distance as add_off_transect_distance,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_orig_geometry as add_orig_geometry,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    bfill_within_patrols as bfill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    buffer_transects as buffer_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    build_hls_ndvi_image as build_hls_ndvi_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    build_slope_image as build_slope_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    combine_names as combine_names,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_field_effort as compute_field_effort,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    convert_column_timezone as convert_column_timezone,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    create_connection_configs as create_connection_configs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    drop_null_columns as drop_null_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    estimate_animal_positions as estimate_animal_positions,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    estimate_utm_crs as estimate_utm_crs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    fetch_events as fetch_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    fetch_patrol_events as fetch_patrol_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    fetch_transects as fetch_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    ffill_within_patrols as ffill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    filter_visited_transects as filter_visited_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    flag_events_intersecting_transect as flag_events_intersecting_transect,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_server_name as get_server_name,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_since_filter as get_since_filter,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_survey_name as get_survey_name,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    join_list_column as join_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    label_features_with_image_stat as label_features_with_image_stat,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    merge_transect_lines as merge_transect_lines,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    parse_df_point as parse_df_point,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    parse_list_column as parse_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    set_dataframe_index as set_dataframe_index,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    simplify_transects as simplify_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    split_connection_configs as split_connection_configs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    to_ee_feature_collection as to_ee_feature_collection,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Configure Google Earth Engine connection

# %%
# parameters

gee_client_params = dict(
    data_source=...,
)

# %%
# call the task


gee_client = (
    set_gee_connection.set_task_instance_id("gee_client")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**gee_client_params)
    .call()
)


# %% [markdown]
# ## Configure EarthRanger and Survey Details

# %%
# parameters

connection_config_params = dict(
    entries=...,
)

# %%
# call the task


connection_config = (
    create_connection_configs.set_task_instance_id("connection_config")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**connection_config_params)
    .call()
)


# %% [markdown]
# ## Split connection configuration

# %%
# parameters

split_connection_config_params = dict()

# %%
# call the task


split_connection_config = (
    split_connection_configs.set_task_instance_id("split_connection_config")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(connection_configs=connection_config, **split_connection_config_params)
    .call()
)


# %% [markdown]
# ## Fetch patrol events

# %%
# parameters

retrieve_patrol_events_params = dict()

# %%
# call the task


retrieve_patrol_events = (
    fetch_patrol_events.set_task_instance_id("retrieve_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**retrieve_patrol_events_params)
    .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
)


# %% [markdown]
# ## Set patrol dataframe index

# %%
# parameters

set_patrol_index_params = dict()

# %%
# call the task


set_patrol_index = (
    set_dataframe_index.set_task_instance_id("set_patrol_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="id", **set_patrol_index_params)
    .mapvalues(argnames=["df"], argvalues=retrieve_patrol_events)
)


# %% [markdown]
# ## Fetch patrol transects from individual surveys

# %%
# parameters

fetch_patrol_transects_params = dict()

# %%
# call the task


fetch_patrol_transects = (
    fetch_transects.set_task_instance_id("fetch_patrol_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**fetch_patrol_transects_params)
    .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
)


# %% [markdown]
# ## Fetch earthranger server name

# %%
# parameters

fetch_earthranger_client_params = dict()

# %%
# call the task


fetch_earthranger_client = (
    get_server_name.set_task_instance_id("fetch_earthranger_client")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**fetch_earthranger_client_params)
    .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
)


# %% [markdown]
# ## Combine connection survey config with patrol events

# %%
# parameters

zip_conn_patrol_events_params = dict()

# %%
# call the task


zip_conn_patrol_events = (
    zip_groupbykey.set_task_instance_id("zip_conn_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[split_connection_config, set_patrol_index],
        **zip_conn_patrol_events_params,
    )
    .call()
)


# %% [markdown]
# ## Fetch events from patrol event ids

# %%
# parameters

fetch_events_from_ids_params = dict()

# %%
# call the task


fetch_events_from_ids = (
    fetch_events.set_task_instance_id("fetch_events_from_ids")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(chunk_size=50, **fetch_events_from_ids_params)
    .mapvalues(
        argnames=["connection_survey", "patrol_events"],
        argvalues=zip_conn_patrol_events,
    )
)


# %% [markdown]
# ## Filter out distancecountpatrol_rep events only

# %%
# parameters

filter_survey_events_params = dict()

# %%
# call the task


filter_survey_events = (
    filter_row_values.set_task_instance_id("filter_survey_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_type",
        values=["distancecountpatrol_rep", "distance_count_patrol_metadata"],
        **filter_survey_events_params,
    )
    .mapvalues(argnames=["df"], argvalues=fetch_events_from_ids)
)


# %% [markdown]
# ## Extract latitude and longitude columns from survey events

# %%
# parameters

extract_lat_long_params = dict()

# %%
# call the task


extract_lat_long = (
    parse_df_point.set_task_instance_id("extract_lat_long")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**extract_lat_long_params)
    .mapvalues(argnames=["df"], argvalues=filter_survey_events)
)


# %% [markdown]
# ## Normalize reported_by column

# %%
# parameters

normalize_reported_by_params = dict()

# %%
# call the task


normalize_reported_by = (
    normalize_json_column.set_task_instance_id("normalize_reported_by")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="reported_by",
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_reported_by_params,
    )
    .mapvalues(argnames=["df"], argvalues=extract_lat_long)
)


# %% [markdown]
# ## Fix reported_by column to extract list values

# %%
# parameters

extract_reported_by_params = dict()

# %%
# call the task


extract_reported_by = (
    join_list_column.set_task_instance_id("extract_reported_by")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="reported_by__name", separator=",", **extract_reported_by_params)
    .mapvalues(argnames=["df"], argvalues=normalize_reported_by)
)


# %% [markdown]
# ## Zip er connection to retained survey values

# %%
# parameters

zip_conn_survey_df_params = dict()

# %%
# call the task


zip_conn_survey_df = (
    zip_groupbykey.set_task_instance_id("zip_conn_survey_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[extract_reported_by, fetch_earthranger_client],
        **zip_conn_survey_df_params,
    )
    .call()
)


# %% [markdown]
# ## Process survey event details

# %%
# parameters

process_survey_event_details_params = dict()

# %%
# call the task


process_survey_event_details = (
    process_events_details.set_task_instance_id("process_survey_event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(map_to_titles=True, ordered=True, **process_survey_event_details_params)
    .mapvalues(argnames=["df", "client"], argvalues=zip_conn_survey_df)
)


# %% [markdown]
# ## Normalize event_details column

# %%
# parameters

normalize_survey_df_params = dict()

# %%
# call the task


normalize_survey_df = (
    normalize_json_column.set_task_instance_id("normalize_survey_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_survey_df_params,
    )
    .mapvalues(argnames=["df"], argvalues=process_survey_event_details)
)


# %% [markdown]
# ## Map survey event column names

# %%
# parameters

map_survey_event_columns_params = dict()

# %%
# call the task


map_survey_event_columns = (
    map_columns.set_task_instance_id("map_survey_event_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=False,
        drop_columns=["id"],
        retain_columns=[
            "serial_number",
            "event_type",
            "time",
            "Latitude",
            "Longitude",
            "reported_by__name",
            "event_details__Transect ID",
            "event_details__Transect_ID",
            "event_details__Team_members",
            "event_details__Team Members",
            "event_details__Number_of_observers",
            "event_details__Number of Observers",
        ],
        rename_columns={
            "time": "time",
            "event_type": "event_type",
            "title": "title",
            "geometry": "geometry",
            "serial_number": "serial_number",
            "patrol_id": "patrol_id",
            "patrol_serial_number": "patrol_serial_number",
            "reported_by__name": "reported_by",
            "Latitude": "latitude",
            "Longitude": "longitude",
            "event_details__Number_of_observers": "Number of Observers",
            "event_details__Team_members": "Team Members",
            "event_details__Transect_ID": "Transect ID",
            "event_details__Number of Observers": "Number of Observers",
            "event_details__Team Members": "Team Members",
            "event_details__Transect ID": "Transect ID",
        },
        **map_survey_event_columns_params,
    )
    .mapvalues(argnames=["df"], argvalues=normalize_survey_df)
)


# %% [markdown]
# ## Parse list column from Team Members column

# %%
# parameters

parse_team_members_params = dict()

# %%
# call the task


parse_team_members = (
    parse_list_column.set_task_instance_id("parse_team_members")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="Team Members", **parse_team_members_params)
    .mapvalues(argnames=["df"], argvalues=map_survey_event_columns)
)


# %% [markdown]
# ## Extract list values from Team members column

# %%
# parameters

join_team_members_params = dict()

# %%
# call the task


join_team_members = (
    join_list_column.set_task_instance_id("join_team_members")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="Team Members", separator=",", **join_team_members_params)
    .mapvalues(argnames=["df"], argvalues=parse_team_members)
)


# %% [markdown]
# ## Drop columns with all null values

# %%
# parameters

drop_null_cols_params = dict()

# %%
# call the task


drop_null_cols = (
    drop_null_columns.set_task_instance_id("drop_null_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**drop_null_cols_params)
    .mapvalues(argnames=["df"], argvalues=join_team_members)
)


# %% [markdown]
# ## Get survey name

# %%
# parameters

retrieve_survey_name_params = dict()

# %%
# call the task


retrieve_survey_name = (
    get_survey_name.set_task_instance_id("retrieve_survey_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**retrieve_survey_name_params)
    .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
)


# %% [markdown]
# ## Combine survey name with event details for filename

# %%
# parameters

combine_survey_event_names_params = dict()

# %%
# call the task


combine_survey_event_names = (
    combine_names.set_task_instance_id("combine_survey_event_names")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(b="_analysis_metadata", **combine_survey_event_names_params)
    .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
)


# %% [markdown]
# ## Zip filename with survey event details dataframe

# %%
# parameters

zip_filename_survey_df_params = dict()

# %%
# call the task


zip_filename_survey_df = (
    zip_groupbykey.set_task_instance_id("zip_filename_survey_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[combine_survey_event_names, drop_null_cols],
        **zip_filename_survey_df_params,
    )
    .call()
)


# %% [markdown]
# ## Persist survey event details dataframe with dynamic filename

# %%
# parameters

persist_survey_event_metadata_params = dict()

# %%
# call the task


persist_survey_event_metadata = (
    persist_df_wrapper.set_task_instance_id("persist_survey_event_metadata")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["csv"],
        filename=None,
        sanitize=False,
        **persist_survey_event_metadata_params,
    )
    .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_survey_df)
)


# %% [markdown]
# ## Zip connection survey split information with metadata csv

# %%
# parameters

zip_connection_metadata_params = dict()

# %%
# call the task


zip_connection_metadata = (
    zip_groupbykey.set_task_instance_id("zip_connection_metadata")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[split_connection_config, drop_null_cols],
        **zip_connection_metadata_params,
    )
    .call()
)


# %% [markdown]
# ## Compute field effort

# %%
# parameters

field_effort_params = dict()

# %%
# call the task


field_effort = (
    compute_field_effort.set_task_instance_id("field_effort")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**field_effort_params)
    .mapvalues(argnames=["connection_survey", "df"], argvalues=zip_connection_metadata)
)


# %% [markdown]
# ## Combine survey name with field effort

# %%
# parameters

combine_survey_field_params = dict()

# %%
# call the task


combine_survey_field = (
    combine_names.set_task_instance_id("combine_survey_field")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(b="_field_effort", **combine_survey_field_params)
    .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
)


# %% [markdown]
# ## Zip filename with field effort

# %%
# parameters

zip_filename_fe_params = dict()

# %%
# call the task


zip_filename_fe = (
    zip_groupbykey.set_task_instance_id("zip_filename_fe")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(sequences=[combine_survey_field, field_effort], **zip_filename_fe_params)
    .call()
)


# %% [markdown]
# ## Persist field effort with dynamic filename

# %%
# parameters

persist_field_effort_params = dict()

# %%
# call the task


persist_field_effort = (
    persist_df_wrapper.set_task_instance_id("persist_field_effort")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["csv"],
        filename=None,
        sanitize=False,
        **persist_field_effort_params,
    )
    .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_fe)
)


# %% [markdown]
# ## Select event_details column from events and merge with patrols

# %%
# parameters

select_event_details_params = dict()

# %%
# call the task


select_event_details = (
    select_columns.set_task_instance_id("select_event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        columns=["event_details"], raise_on_missing=False, **select_event_details_params
    )
    .mapvalues(argnames=["df"], argvalues=fetch_events_from_ids)
)


# %% [markdown]
# ## Zip patrol events and filtered event dataframe

# %%
# parameters

zip_patrol_events_df_params = dict()

# %%
# call the task


zip_patrol_events_df = (
    zip_groupbykey.set_task_instance_id("zip_patrol_events_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[set_patrol_index, select_event_details],
        **zip_patrol_events_df_params,
    )
    .call()
)


# %% [markdown]
# ## Merge patrols with events event_details column

# %%
# parameters

merge_patrol_events_params = dict()

# %%
# call the task


merge_patrol_events = (
    merge_two_dataframes.set_task_instance_id("merge_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        how="left",
        left_on=None,
        right_on=None,
        left_index=True,
        right_index=True,
        fillna_value=None,
        on=None,
        **merge_patrol_events_params,
    )
    .mapvalues(argnames=["left", "right"], argvalues=zip_patrol_events_df)
)


# %% [markdown]
# ## Convert timezone to UTC

# %%
# parameters

convert_tz_utc_params = dict()

# %%
# call the task


convert_tz_utc = (
    convert_column_timezone.set_task_instance_id("convert_tz_utc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="time", time_range=time_range, **convert_tz_utc_params)
    .mapvalues(argnames=["df"], argvalues=merge_patrol_events)
)


# %% [markdown]
# ## Normalize patrol event_details column

# %%
# parameters

normalize_event_details_params = dict()

# %%
# call the task


normalize_event_details = (
    normalize_json_column.set_task_instance_id("normalize_event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_event_details_params,
    )
    .mapvalues(argnames=["df"], argvalues=convert_tz_utc)
)


# %% [markdown]
# ## Map patrol df columns

# %%
# parameters

map_patrol_df_params = dict()

# %%
# call the task


map_patrol_df = (
    map_columns.set_task_instance_id("map_patrol_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=None,
        raise_if_not_found=False,
        retain_columns=None,
        rename_columns={
            "event_details__distancecountpatrol_numberofobservers": "num_observers",
            "event_details__distancecountpatrol_teammembers": "Team Members",
            "event_details__distancecountpatrol_transectid": "transect_id",
            "event_details__distancecountwildlife_distancetocentre": "dist_to_centre",
            "event_details__distancecountwildlife_numberofjuveniles": "num_juveniles",
            "event_details__distancecountwildlife_radialangle": "radialangle",
            "event_details__distancecountwildlife_species": "species",
            "event_details__distancecountwildlife_totalcount": "totalcount",
            "event_details__Transect_ID": "transect_id_v2",
            "event_details__Team_members": "Team Members",
            "event_details__Number_of_observers": "num_observers",
            "event_details__Number_of_Observers": "num_observers",
            "event_details__Number of Observers": "num_observers",
        },
        **map_patrol_df_params,
    )
    .mapvalues(argnames=["df"], argvalues=normalize_event_details)
)


# %% [markdown]
# ## Normalize transect_id column name across schemas

# %%
# parameters

normalize_transect_id_params = dict()

# %%
# call the task


normalize_transect_id = (
    map_columns.set_task_instance_id("normalize_transect_id")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=False,
        drop_columns=[],
        retain_columns=[],
        rename_columns={"transect_id_v2": "transect_id"},
        **normalize_transect_id_params,
    )
    .mapvalues(argnames=["df"], argvalues=map_patrol_df)
)


# %% [markdown]
# ## Parse list column from Transect ID column

# %%
# parameters

parse_transect_id_params = dict()

# %%
# call the task


parse_transect_id = (
    parse_list_column.set_task_instance_id("parse_transect_id")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="transect_id", **parse_transect_id_params)
    .mapvalues(argnames=["df"], argvalues=normalize_transect_id)
)


# %% [markdown]
# ## Extract list values from Transect ID column

# %%
# parameters

join_transect_id_params = dict()

# %%
# call the task


join_transect_id = (
    join_list_column.set_task_instance_id("join_transect_id")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="transect_id", separator=",", **join_transect_id_params)
    .mapvalues(argnames=["df"], argvalues=parse_transect_id)
)


# %% [markdown]
# ## Backward fill patrol event values within patrols

# %%
# parameters

bfill_patrol_events_params = dict()

# %%
# call the task


bfill_patrol_events = (
    bfill_within_patrols.set_task_instance_id("bfill_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        group_col="patrol_serial_number",
        columns=["transect_id", "num_observers"],
        skip_if_missing=True,
        **bfill_patrol_events_params,
    )
    .mapvalues(argnames=["df"], argvalues=join_transect_id)
)


# %% [markdown]
# ## Forward fill patrol event values within patrols

# %%
# parameters

ffill_patrol_events_params = dict()

# %%
# call the task


ffill_patrol_events = (
    ffill_within_patrols.set_task_instance_id("ffill_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        group_col="patrol_serial_number",
        columns=["transect_id", "num_observers"],
        skip_if_missing=True,
        **ffill_patrol_events_params,
    )
    .mapvalues(argnames=["df"], argvalues=bfill_patrol_events)
)


# %% [markdown]
# ## Filter out distancecountwildlife_rep only

# %%
# parameters

filter_wildlife_rep_params = dict()

# %%
# call the task


filter_wildlife_rep = (
    filter_row_values.set_task_instance_id("filter_wildlife_rep")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_type",
        values=["distancecountwildlife_rep"],
        **filter_wildlife_rep_params,
    )
    .mapvalues(argnames=["df"], argvalues=ffill_patrol_events)
)


# %% [markdown]
# ## Zip connection survey name with patrol events

# %%
# parameters

zip_conn_surv_name_df_params = dict()

# %%
# call the task


zip_conn_surv_name_df = (
    zip_groupbykey.set_task_instance_id("zip_conn_surv_name_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[filter_wildlife_rep, retrieve_survey_name],
        **zip_conn_surv_name_df_params,
    )
    .call()
)


# %% [markdown]
# ## Add survey_id column to patrol events df

# %%
# parameters

add_survey_column_params = dict()

# %%
# call the task


add_survey_column = (
    add_constant_column.set_task_instance_id("add_survey_column")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="survey_id", **add_survey_column_params)
    .mapvalues(argnames=["df", "value"], argvalues=zip_conn_surv_name_df)
)


# %% [markdown]
# ## Convert retrieved transects crs to utm_crs

# %%
# parameters

convert_transects_utm_params = dict()

# %%
# call the task


convert_transects_utm = (
    estimate_utm_crs.set_task_instance_id("convert_transects_utm")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**convert_transects_utm_params)
    .mapvalues(argnames=["geodataframe"], argvalues=fetch_patrol_transects)
)


# %% [markdown]
# ## Zip transect df and utm crs value

# %%
# parameters

zip_transect_df_crs_params = dict()

# %%
# call the task


zip_transect_df_crs = (
    zip_groupbykey.set_task_instance_id("zip_transect_df_crs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[convert_transects_utm, fetch_patrol_transects],
        **zip_transect_df_crs_params,
    )
    .call()
)


# %% [markdown]
# ## Reproject transects to utm crs

# %%
# parameters

reproject_transects_utm_params = dict()

# %%
# call the task


reproject_transects_utm = (
    reproject_gdf.set_task_instance_id("reproject_transects_utm")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**reproject_transects_utm_params)
    .mapvalues(argnames=["target_crs", "gdf"], argvalues=zip_transect_df_crs)
)


# %% [markdown]
# ## Zip patrol df and crs

# %%
# parameters

zip_patrol_df_crs_params = dict()

# %%
# call the task


zip_patrol_df_crs = (
    zip_groupbykey.set_task_instance_id("zip_patrol_df_crs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[convert_transects_utm, add_survey_column], **zip_patrol_df_crs_params
    )
    .call()
)


# %% [markdown]
# ## Reproject patrol events to utm crs

# %%
# parameters

patrol_events_utm_params = dict()

# %%
# call the task


patrol_events_utm = (
    reproject_gdf.set_task_instance_id("patrol_events_utm")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**patrol_events_utm_params)
    .mapvalues(argnames=["target_crs", "gdf"], argvalues=zip_patrol_df_crs)
)


# %% [markdown]
# ## Zip patrol events and transects

# %%
# parameters

zip_patrol_transects_params = dict()

# %%
# call the task


zip_patrol_transects = (
    zip_groupbykey.set_task_instance_id("zip_patrol_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[patrol_events_utm, reproject_transects_utm],
        **zip_patrol_transects_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate distance from observers position to transect centerline

# %%
# parameters

observers_distance_params = dict()

# %%
# call the task


observers_distance = (
    add_off_transect_distance.set_task_instance_id("observers_distance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        distance_column="off_transect_dist",
        transect_id_column="transect_id",
        transect_name_column="name",
        **observers_distance_params,
    )
    .mapvalues(argnames=["patrol_events", "transects"], argvalues=zip_patrol_transects)
)


# %% [markdown]
# ## Exclude row values where off_transect_dist == -1

# %%
# parameters

exclude_neg_off_transects_params = dict()

# %%
# call the task


exclude_neg_off_transects = (
    filter_numeric_df.set_task_instance_id("exclude_neg_off_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="off_transect_dist",
        value=-1,
        reset_index=True,
        coerce_numeric=True,
        op="ne",
        **exclude_neg_off_transects_params,
    )
    .mapvalues(argnames=["df"], argvalues=observers_distance)
)


# %% [markdown]
# ## Add orig geometry from existing geometry

# %%
# parameters

add_orig_geom_params = dict()

# %%
# call the task


add_orig_geom = (
    add_orig_geometry.set_task_instance_id("add_orig_geom")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**add_orig_geom_params)
    .mapvalues(argnames=["gdf"], argvalues=exclude_neg_off_transects)
)


# %% [markdown]
# ## Estimate animal position

# %%
# parameters

estimate_animal_position_params = dict()

# %%
# call the task


estimate_animal_position = (
    estimate_animal_positions.set_task_instance_id("estimate_animal_position")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        distance_column="dist_to_centre",
        angle_column="radialangle",
        preserve_original_as="orig_geometry",
        **estimate_animal_position_params,
    )
    .mapvalues(argnames=["patrol_events"], argvalues=add_orig_geom)
)


# %% [markdown]
# ## Zip estimated patrol events and transects

# %%
# parameters

zip_est_patrol_transects_params = dict()

# %%
# call the task


zip_est_patrol_transects = (
    zip_groupbykey.set_task_instance_id("zip_est_patrol_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[estimate_animal_position, reproject_transects_utm],
        **zip_est_patrol_transects_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate orthogonal distance

# %%
# parameters

compute_ortho_dist_params = dict()

# %%
# call the task


compute_ortho_dist = (
    add_off_transect_distance.set_task_instance_id("compute_ortho_dist")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        distance_column="ortho_dist",
        transect_id_column="transect_id",
        transect_name_column="name",
        **compute_ortho_dist_params,
    )
    .mapvalues(
        argnames=["patrol_events", "transects"], argvalues=zip_est_patrol_transects
    )
)


# %% [markdown]
# ## Exclude row values where ortho_dist == -1

# %%
# parameters

exclude_neg_ortho_dist_params = dict()

# %%
# call the task


exclude_neg_ortho_dist = (
    filter_numeric_df.set_task_instance_id("exclude_neg_ortho_dist")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="ortho_dist",
        value=-1,
        reset_index=True,
        coerce_numeric=True,
        op="ne",
        **exclude_neg_ortho_dist_params,
    )
    .mapvalues(argnames=["df"], argvalues=compute_ortho_dist)
)


# %% [markdown]
# ## Merge transect lines

# %%
# parameters

merge_transects_params = dict()

# %%
# call the task


merge_transects = (
    merge_transect_lines.set_task_instance_id("merge_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**merge_transects_params)
    .mapvalues(argnames=["transects"], argvalues=reproject_transects_utm)
)


# %% [markdown]
# ## Simplify transects by a tolerance of 50 meters

# %%
# parameters

simplify_tolerance_params = dict()

# %%
# call the task


simplify_tolerance = (
    simplify_transects.set_task_instance_id("simplify_tolerance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(tolerance=50, **simplify_tolerance_params)
    .mapvalues(argnames=["transects"], argvalues=merge_transects)
)


# %% [markdown]
# ## Buffer transects by 500 meters on each side with flat cap style and 5 meter resolution

# %%
# parameters

buffer_transect_segments_params = dict()

# %%
# call the task


buffer_transect_segments = (
    buffer_transects.set_task_instance_id("buffer_transect_segments")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        cap_style="flat",
        single_sided=False,
        resolution=5,
        distance=500,
        **buffer_transect_segments_params,
    )
    .mapvalues(argnames=["transects"], argvalues=simplify_tolerance)
)


# %% [markdown]
# ## Zip patrol events with buffered transects

# %%
# parameters

zip_events_buff_trans_params = dict()

# %%
# call the task


zip_events_buff_trans = (
    zip_groupbykey.set_task_instance_id("zip_events_buff_trans")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[exclude_neg_ortho_dist, buffer_transect_segments],
        **zip_events_buff_trans_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events that intersect with transects

# %%
# parameters

filter_intersecting_events_params = dict()

# %%
# call the task


filter_intersecting_events = (
    flag_events_intersecting_transect.set_task_instance_id("filter_intersecting_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        intersects_column="intersects_transect",
        transect_id_column="transect_id",
        transect_name_column="name",
        index_column="id",
        **filter_intersecting_events_params,
    )
    .mapvalues(argnames=["patrol_events", "transects"], argvalues=zip_events_buff_trans)
)


# %% [markdown]
# ## Zip filtered events with buffered transects for visited-transect filter

# %%
# parameters

zip_filtered_events_trans_params = dict()

# %%
# call the task


zip_filtered_events_trans = (
    zip_groupbykey.set_task_instance_id("zip_filtered_events_trans")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[filter_intersecting_events, buffer_transect_segments],
        **zip_filtered_events_trans_params,
    )
    .call()
)


# %% [markdown]
# ## Keep only transects visited by at least one intersecting event

# %%
# parameters

visited_transects_params = dict()

# %%
# call the task


visited_transects = (
    filter_visited_transects.set_task_instance_id("visited_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        intersects_column="intersects_transect",
        transect_id_column="transect_id",
        transect_name_column="name",
        **visited_transects_params,
    )
    .mapvalues(
        argnames=["patrol_events", "transects"], argvalues=zip_filtered_events_trans
    )
)


# %% [markdown]
# ## Convert transects gdf back to epsg:4326 for export and labeling with imagery

# %%
# parameters

reproject_transects_params = dict()

# %%
# call the task


reproject_transects = (
    reproject_gdf.set_task_instance_id("reproject_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(target_crs="epsg:4326", **reproject_transects_params)
    .mapvalues(argnames=["gdf"], argvalues=visited_transects)
)


# %% [markdown]
# ## Get since filter from survey start date on connection config

# %%
# parameters

get_since_conf_filter_params = dict()

# %%
# call the task


get_since_conf_filter = (
    get_since_filter.set_task_instance_id("get_since_conf_filter")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**get_since_conf_filter_params)
    .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
)


# %% [markdown]
# ## Zip transects df with since filter

# %%
# parameters

zip_df_since_params = dict()

# %%
# call the task


zip_df_since = (
    zip_groupbykey.set_task_instance_id("zip_df_since")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[get_since_conf_filter, reproject_transects], **zip_df_since_params
    )
    .call()
)


# %% [markdown]
# ## Add since filter to transect df

# %%
# parameters

add_since_transects_params = dict()

# %%
# call the task


add_since_transects = (
    add_constant_column.set_task_instance_id("add_since_transects")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="survey_date", **add_since_transects_params)
    .mapvalues(argnames=["value", "df"], argvalues=zip_df_since)
)


# %% [markdown]
# ## Convert transects to feature collection

# %%
# parameters

convert_trans_ee_params = dict()

# %%
# call the task


convert_trans_ee = (
    to_ee_feature_collection.set_task_instance_id("convert_trans_ee")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=gee_client, **convert_trans_ee_params)
    .mapvalues(argnames=["gdf"], argvalues=add_since_transects)
)


# %% [markdown]
# ## Zip aoi and since filter for imagery retrieval

# %%
# parameters

zip_aoi_since_params = dict()

# %%
# call the task


zip_aoi_since = (
    zip_groupbykey.set_task_instance_id("zip_aoi_since")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[convert_trans_ee, get_since_conf_filter], **zip_aoi_since_params
    )
    .call()
)


# %% [markdown]
# ## Build hls ndvi image

# %%
# parameters

hls_ndvi_image_params = dict()

# %%
# call the task


hls_ndvi_image = (
    build_hls_ndvi_image.set_task_instance_id("hls_ndvi_image")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=gee_client,
        ndvi_window_days=None,
        max_cloud_cover=30,
        ndvi_band_name="NDVI_HSL",
        **hls_ndvi_image_params,
    )
    .mapvalues(argnames=["aoi", "since"], argvalues=zip_aoi_since)
)


# %% [markdown]
# ## Build slope image

# %%
# parameters

create_slope_image_params = dict()

# %%
# call the task


create_slope_image = (
    build_slope_image.set_task_instance_id("create_slope_image")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=gee_client, dem_asset="USGS/SRTMGL1_003", **create_slope_image_params
    )
    .call()
)


# %% [markdown]
# ## Add NDVI_HSL column to transects column

# %%
# parameters

label_ndvi_hsl_params = dict()

# %%
# call the task


label_ndvi_hsl = (
    label_features_with_image_stat.set_task_instance_id("label_ndvi_hsl")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        image=create_slope_image,
        out_column="NDVI_HSL",
        region_reducer=None,
        scale=30.0,
        reducer_key="mean",
        **label_ndvi_hsl_params,
    )
    .mapvalues(argnames=["gdf"], argvalues=add_since_transects)
)


# %% [markdown]
# ## Zip df with since filter and ndvi

# %%
# parameters

zip_df_ndvi_params = dict()

# %%
# call the task


zip_df_ndvi = (
    zip_groupbykey.set_task_instance_id("zip_df_ndvi")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(sequences=[get_since_conf_filter, label_ndvi_hsl], **zip_df_ndvi_params)
    .call()
)


# %% [markdown]
# ## Add img_date_hsl_ndvi to transects column

# %%
# parameters

add_img_date_hsl_ndvi_params = dict()

# %%
# call the task


add_img_date_hsl_ndvi = (
    add_constant_column.set_task_instance_id("add_img_date_hsl_ndvi")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="img_date_hsl_ndvi", **add_img_date_hsl_ndvi_params)
    .mapvalues(argnames=["value", "df"], argvalues=zip_df_ndvi)
)


# %% [markdown]
# ## Add slope column to transects column

# %%
# parameters

label_slope_params = dict()

# %%
# call the task


label_slope = (
    label_features_with_image_stat.set_task_instance_id("label_slope")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        image=create_slope_image,
        out_column="slope",
        region_reducer=None,
        scale=30.0,
        reducer_key="mean",
        **label_slope_params,
    )
    .mapvalues(argnames=["gdf"], argvalues=add_img_date_hsl_ndvi)
)


# %% [markdown]
# ## Filter column transects for merging with patrol events

# %%
# parameters

filter_transect_columns_params = dict()

# %%
# call the task


filter_transect_columns = (
    select_columns.set_task_instance_id("filter_transect_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        columns=["name", "img_date_hsl_ndvi", "NDVI_HSL", "slope", "geometry"],
        raise_on_missing=True,
        **filter_transect_columns_params,
    )
    .mapvalues(argnames=["df"], argvalues=label_slope)
)


# %% [markdown]
# ## Exclude geometry from transects

# %%
# parameters

exclude_geom_params = dict()

# %%
# call the task


exclude_geom = (
    select_columns.set_task_instance_id("exclude_geom")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        columns=["name", "img_date_hsl_ndvi", "NDVI_HSL", "slope"],
        raise_on_missing=True,
        **exclude_geom_params,
    )
    .mapvalues(argnames=["df"], argvalues=filter_transect_columns)
)


# %% [markdown]
# ## Zip patrols df and transects df

# %%
# parameters

zip_patrol_transects_df_params = dict()

# %%
# call the task


zip_patrol_transects_df = (
    zip_groupbykey.set_task_instance_id("zip_patrol_transects_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[filter_intersecting_events, exclude_geom],
        **zip_patrol_transects_df_params,
    )
    .call()
)


# %% [markdown]
# ## Merge patrol events with transects

# %%
# parameters

merge_filtered_patrols_params = dict()

# %%
# call the task


merge_filtered_patrols = (
    merge_two_dataframes.set_task_instance_id("merge_filtered_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left_on="transect_id",
        right_on="name",
        how="left",
        left_index=False,
        right_index=False,
        fillna_value=None,
        on=None,
        **merge_filtered_patrols_params,
    )
    .mapvalues(argnames=["left", "right"], argvalues=zip_patrol_transects_df)
)


# %% [markdown]
# ## Select patrol event columns for export

# %%
# parameters

select_patrol_event_cols_params = dict()

# %%
# call the task


select_patrol_event_cols = (
    select_columns.set_task_instance_id("select_patrol_event_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        columns=[
            "transect_id",
            "level_1",
            "title",
            "patrol_id",
            "patrol_serial_number",
            "totalcount",
            "num_juveniles",
            "event_type",
            "num_observers",
            "dist_to_centre",
            "geometry",
            "species",
            "time",
            "serial_number",
            "radialangle",
            "survey_id",
            "off_transect_dist",
            "orig_geometry",
            "ortho_dist",
            "intersects_transect",
            "img_date_hsl_ndvi",
            "NDVI_HSL",
            "slope",
        ],
        raise_on_missing=False,
        **select_patrol_event_cols_params,
    )
    .mapvalues(argnames=["df"], argvalues=merge_filtered_patrols)
)


# %% [markdown]
# ## Combine survey name with patrol events for filename

# %%
# parameters

combine_patrol_event_names_params = dict()

# %%
# call the task


combine_patrol_event_names = (
    combine_names.set_task_instance_id("combine_patrol_event_names")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(b="_analysis_data", **combine_patrol_event_names_params)
    .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
)


# %% [markdown]
# ## Zip filename with patrol events dataframe

# %%
# parameters

zip_filename_patrol_df_params = dict()

# %%
# call the task


zip_filename_patrol_df = (
    zip_groupbykey.set_task_instance_id("zip_filename_patrol_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[combine_patrol_event_names, select_patrol_event_cols],
        **zip_filename_patrol_df_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol events as csv

# %%
# parameters

persist_patrol_events_csv_params = dict()

# %%
# call the task


persist_patrol_events_csv = (
    persist_df_wrapper.set_task_instance_id("persist_patrol_events_csv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["csv"],
        filename=None,
        sanitize=False,
        **persist_patrol_events_csv_params,
    )
    .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_patrol_df)
)


# %% [markdown]
# ## Select columns to persist as gpkg

# %%
# parameters

select_gpkg_columns_params = dict()

# %%
# call the task


select_gpkg_columns = (
    select_columns.set_task_instance_id("select_gpkg_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        columns=[
            "serial_number",
            "transect_id",
            "dist_to_centre",
            "ortho_dist",
            "intersects_transect",
            "geometry",
        ],
        raise_on_missing=False,
        **select_gpkg_columns_params,
    )
    .mapvalues(argnames=["df"], argvalues=select_patrol_event_cols)
)


# %% [markdown]
# ## Combine survey name with patrol events for gpkg filename

# %%
# parameters

combine_gpkg_name_params = dict()

# %%
# call the task


combine_gpkg_name = (
    combine_names.set_task_instance_id("combine_gpkg_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(b="_events", **combine_gpkg_name_params)
    .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
)


# %% [markdown]
# ## Zip filename with gpkg columns df

# %%
# parameters

zip_filename_gpkg_df_params = dict()

# %%
# call the task


zip_filename_gpkg_df = (
    zip_groupbykey.set_task_instance_id("zip_filename_gpkg_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[combine_gpkg_name, select_gpkg_columns],
        **zip_filename_gpkg_df_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol events as gpkg

# %%
# parameters

persist_patrol_events_gpkg_params = dict()

# %%
# call the task


persist_patrol_events_gpkg = (
    persist_df_wrapper.set_task_instance_id("persist_patrol_events_gpkg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["gpkg"],
        filename=None,
        sanitize=False,
        **persist_patrol_events_gpkg_params,
    )
    .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_gpkg_df)
)


# %% [markdown]
# ## Combine survey name with transects for gpkg filename

# %%
# parameters

combine_transect_gpkg_name_params = dict()

# %%
# call the task


combine_transect_gpkg_name = (
    combine_names.set_task_instance_id("combine_transect_gpkg_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(b="_transects", **combine_transect_gpkg_name_params)
    .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
)


# %% [markdown]
# ## Zip filename with transects df for gpkg export

# %%
# parameters

zip_filename_transect_df_params = dict()

# %%
# call the task


zip_filename_transect_df = (
    zip_groupbykey.set_task_instance_id("zip_filename_transect_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[combine_transect_gpkg_name, filter_transect_columns],
        **zip_filename_transect_df_params,
    )
    .call()
)


# %% [markdown]
# ## Persist transects as gpkg

# %%
# parameters

persist_transects_gpkg_params = dict()

# %%
# call the task


persist_transects_gpkg = (
    persist_df_wrapper.set_task_instance_id("persist_transects_gpkg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["gpkg"],
        filename=None,
        sanitize=False,
        **persist_transects_gpkg_params,
    )
    .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_transect_df)
)


# %% [markdown]
# ## Combine survey name with original transects for gpkg filename

# %%
# parameters

combine_orig_transect_gpkg_name_params = dict()

# %%
# call the task


combine_orig_transect_gpkg_name = (
    combine_names.set_task_instance_id("combine_orig_transect_gpkg_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(b="_orig_transects", **combine_orig_transect_gpkg_name_params)
    .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
)


# %% [markdown]
# ## Zip filename with original transects df for gpkg export

# %%
# parameters

zip_filename_orig_transect_df_params = dict()

# %%
# call the task


zip_filename_orig_transect_df = (
    zip_groupbykey.set_task_instance_id("zip_filename_orig_transect_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[combine_orig_transect_gpkg_name, reproject_transects],
        **zip_filename_orig_transect_df_params,
    )
    .call()
)


# %% [markdown]
# ## Persist original transects as gpkg

# %%
# parameters

persist_orig_transects_gpkg_params = dict()

# %%
# call the task


persist_orig_transects_gpkg = (
    persist_df_wrapper.set_task_instance_id("persist_orig_transects_gpkg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["gpkg"],
        filename=None,
        sanitize=False,
        **persist_orig_transects_gpkg_params,
    )
    .mapvalues(
        argnames=["filename_prefix", "df"], argvalues=zip_filename_orig_transect_df
    )
)


# %% [markdown]
# ## Overall dashboard

# %%
# parameters

overall_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


overall_dashboard = (
    gather_dashboard.set_task_instance_id("overall_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **overall_dashboard_params,
    )
    .call()
)
