# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_big_life.tasks import filter_numeric_df as filter_numeric_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    format_text_column as format_text_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    parse_list_column as parse_list_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_constant_column as add_constant_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_off_transect_distance as add_off_transect_distance,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_orig_geometry as add_orig_geometry,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    bfill_within_patrols as bfill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    buffer_transects as buffer_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    build_hls_ndvi_image as build_hls_ndvi_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    build_slope_image as build_slope_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    combine_names as combine_names,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_field_effort as compute_field_effort,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    convert_column_timezone as convert_column_timezone,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    create_connection_configs as create_connection_configs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    drop_null_columns as drop_null_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    estimate_animal_positions as estimate_animal_positions,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    estimate_utm_crs as estimate_utm_crs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    extract_notes_text as extract_notes_text,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    fetch_events as fetch_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    fetch_patrol_events as fetch_patrol_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    fetch_transects as fetch_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    ffill_within_patrols as ffill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    filter_visited_transects as filter_visited_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    flag_events_intersecting_transect as flag_events_intersecting_transect,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_server_name as get_server_name,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_since_filter as get_since_filter,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_survey_name as get_survey_name,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    join_list_column as join_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    label_features_with_image_stat as label_features_with_image_stat,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    merge_transect_lines as merge_transect_lines,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    normalize_name_spaces as normalize_name_spaces,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    parse_df_point as parse_df_point,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    set_dataframe_index as set_dataframe_index,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    simplify_transects as simplify_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    split_connection_configs as split_connection_configs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    to_ee_feature_collection as to_ee_feature_collection,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    gee_client = (
        set_gee_connection.validate()
        .set_task_instance_id("gee_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("gee_client") or {}))
        .call()
    )

    connection_config = (
        create_connection_configs.validate()
        .set_task_instance_id("connection_config")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("connection_config") or {}))
        .call()
    )

    split_connection_config = (
        split_connection_configs.validate()
        .set_task_instance_id("split_connection_config")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            connection_configs=connection_config,
            **(params_dict.get("split_connection_config") or {}),
        )
        .call()
    )

    retrieve_patrol_events = (
        fetch_patrol_events.validate()
        .set_task_instance_id("retrieve_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("retrieve_patrol_events") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
    )

    set_patrol_index = (
        set_dataframe_index.validate()
        .set_task_instance_id("set_patrol_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="id", **(params_dict.get("set_patrol_index") or {}))
        .mapvalues(argnames=["df"], argvalues=retrieve_patrol_events)
    )

    fetch_patrol_transects = (
        fetch_transects.validate()
        .set_task_instance_id("fetch_patrol_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("fetch_patrol_transects") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
    )

    fetch_earthranger_client = (
        get_server_name.validate()
        .set_task_instance_id("fetch_earthranger_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("fetch_earthranger_client") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
    )

    zip_conn_patrol_events = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_conn_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[split_connection_config, set_patrol_index],
            **(params_dict.get("zip_conn_patrol_events") or {}),
        )
        .call()
    )

    fetch_events_from_ids = (
        fetch_events.validate()
        .set_task_instance_id("fetch_events_from_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(chunk_size=50, **(params_dict.get("fetch_events_from_ids") or {}))
        .mapvalues(
            argnames=["connection_survey", "patrol_events"],
            argvalues=zip_conn_patrol_events,
        )
    )

    filter_survey_events = (
        filter_row_values.validate()
        .set_task_instance_id("filter_survey_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_type",
            values=["distancecountpatrol_rep", "distance_count_patrol_metadata"],
            **(params_dict.get("filter_survey_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=fetch_events_from_ids)
    )

    extract_lat_long = (
        parse_df_point.validate()
        .set_task_instance_id("extract_lat_long")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("extract_lat_long") or {}))
        .mapvalues(argnames=["df"], argvalues=filter_survey_events)
    )

    normalize_reported_by = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="reported_by",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_reported_by") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=extract_lat_long)
    )

    extract_reported_by = (
        join_list_column.validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="reported_by__name",
            separator=",",
            **(params_dict.get("extract_reported_by") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_reported_by)
    )

    zip_conn_survey_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_conn_survey_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[extract_reported_by, fetch_earthranger_client],
            **(params_dict.get("zip_conn_survey_df") or {}),
        )
        .call()
    )

    process_survey_event_details = (
        process_events_details.validate()
        .set_task_instance_id("process_survey_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_survey_event_details") or {}),
        )
        .mapvalues(argnames=["df", "client"], argvalues=zip_conn_survey_df)
    )

    normalize_survey_df = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_survey_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_survey_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=process_survey_event_details)
    )

    map_survey_event_columns = (
        map_columns.validate()
        .set_task_instance_id("map_survey_event_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=False,
            drop_columns=["id"],
            retain_columns=[
                "serial_number",
                "event_type",
                "time",
                "Latitude",
                "Longitude",
                "reported_by__name",
                "event_details__Transect ID",
                "event_details__Transect_ID",
                "event_details__Team_members",
                "event_details__Team Members",
                "event_details__Number_of_observers",
                "event_details__Number of Observers",
            ],
            rename_columns={
                "time": "time",
                "event_type": "event_type",
                "title": "title",
                "geometry": "geometry",
                "serial_number": "serial_number",
                "patrol_id": "patrol_id",
                "patrol_serial_number": "patrol_serial_number",
                "reported_by__name": "reported_by",
                "Latitude": "latitude",
                "Longitude": "longitude",
                "event_details__Number_of_observers": "Number of Observers",
                "event_details__Team_members": "Team Members",
                "event_details__Transect_ID": "Transect ID",
                "event_details__Number of Observers": "Number of Observers",
                "event_details__Team Members": "Team Members",
                "event_details__Transect ID": "Transect ID",
            },
            **(params_dict.get("map_survey_event_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_survey_df)
    )

    parse_team_members = (
        parse_list_column.validate()
        .set_task_instance_id("parse_team_members")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="Team Members", **(params_dict.get("parse_team_members") or {}))
        .mapvalues(argnames=["df"], argvalues=map_survey_event_columns)
    )

    join_team_members = (
        join_list_column.validate()
        .set_task_instance_id("join_team_members")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="Team Members",
            separator=",",
            **(params_dict.get("join_team_members") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=parse_team_members)
    )

    drop_null_cols = (
        drop_null_columns.validate()
        .set_task_instance_id("drop_null_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("drop_null_cols") or {}))
        .mapvalues(argnames=["df"], argvalues=join_team_members)
    )

    retrieve_survey_name = (
        get_survey_name.validate()
        .set_task_instance_id("retrieve_survey_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("retrieve_survey_name") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
    )

    combine_survey_event_names = (
        combine_names.validate()
        .set_task_instance_id("combine_survey_event_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            b="_analysis_metadata",
            **(params_dict.get("combine_survey_event_names") or {}),
        )
        .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
    )

    zip_filename_survey_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_filename_survey_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_survey_event_names, drop_null_cols],
            **(params_dict.get("zip_filename_survey_df") or {}),
        )
        .call()
    )

    persist_survey_event_metadata = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_survey_event_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["csv"],
            filename=None,
            sanitize=False,
            **(params_dict.get("persist_survey_event_metadata") or {}),
        )
        .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_survey_df)
    )

    zip_connection_metadata = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_connection_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[split_connection_config, drop_null_cols],
            **(params_dict.get("zip_connection_metadata") or {}),
        )
        .call()
    )

    field_effort = (
        compute_field_effort.validate()
        .set_task_instance_id("field_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("field_effort") or {}))
        .mapvalues(
            argnames=["connection_survey", "df"], argvalues=zip_connection_metadata
        )
    )

    combine_survey_field = (
        combine_names.validate()
        .set_task_instance_id("combine_survey_field")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(b="_field_effort", **(params_dict.get("combine_survey_field") or {}))
        .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
    )

    zip_filename_fe = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_filename_fe")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_survey_field, field_effort],
            **(params_dict.get("zip_filename_fe") or {}),
        )
        .call()
    )

    persist_field_effort = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_field_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["csv"],
            filename=None,
            sanitize=False,
            **(params_dict.get("persist_field_effort") or {}),
        )
        .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_fe)
    )

    select_event_details = (
        select_columns.validate()
        .set_task_instance_id("select_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["event_details", "notes"],
            raise_on_missing=False,
            **(params_dict.get("select_event_details") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=fetch_events_from_ids)
    )

    zip_patrol_events_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_patrol_events_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[set_patrol_index, select_event_details],
            **(params_dict.get("zip_patrol_events_df") or {}),
        )
        .call()
    )

    merge_patrol_events = (
        merge_two_dataframes.validate()
        .set_task_instance_id("merge_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            how="left",
            left_on=None,
            right_on=None,
            left_index=True,
            right_index=True,
            fillna_value=None,
            on=None,
            **(params_dict.get("merge_patrol_events") or {}),
        )
        .mapvalues(argnames=["left", "right"], argvalues=zip_patrol_events_df)
    )

    convert_tz_utc = (
        convert_column_timezone.validate()
        .set_task_instance_id("convert_tz_utc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="time",
            time_range=time_range,
            **(params_dict.get("convert_tz_utc") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=merge_patrol_events)
    )

    normalize_event_details = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_event_details") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=convert_tz_utc)
    )

    map_patrol_df = (
        map_columns.validate()
        .set_task_instance_id("map_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=None,
            raise_if_not_found=False,
            retain_columns=None,
            rename_columns={
                "event_details__distancecountpatrol_numberofobservers": "num_observers",
                "event_details__distancecountpatrol_teammembers": "Team Members",
                "event_details__distancecountpatrol_transectid": "transect_id",
                "event_details__distancecountwildlife_distancetocentre": "dist_to_centre",
                "event_details__distancecountwildlife_numberofjuveniles": "num_juveniles",
                "event_details__distancecountwildlife_radialangle": "radialangle",
                "event_details__distancecountwildlife_species": "species",
                "event_details__distancecountwildlife_totalcount": "totalcount",
                "event_details__Transect_ID": "transect_id_v2",
                "event_details__Team_members": "Team Members",
                "event_details__Number_of_observers": "num_observers",
                "event_details__Number_of_Observers": "num_observers",
                "event_details__Number of Observers": "num_observers",
                "event_details__Species": "species",
                "event_details__Total Count": "totalcount",
                "event_details__Number of Juveniles": "num_juveniles",
                "event_details__Radial Angle": "radialangle",
                "event_details__Distance to Centre (m)": "dist_to_centre",
            },
            **(params_dict.get("map_patrol_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_event_details)
    )

    normalize_transect_id = (
        map_columns.validate()
        .set_task_instance_id("normalize_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=False,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"transect_id_v2": "transect_id"},
            **(params_dict.get("normalize_transect_id") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=map_patrol_df)
    )

    parse_transect_id = (
        parse_list_column.validate()
        .set_task_instance_id("parse_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="transect_id", **(params_dict.get("parse_transect_id") or {}))
        .mapvalues(argnames=["df"], argvalues=normalize_transect_id)
    )

    join_transect_id = (
        join_list_column.validate()
        .set_task_instance_id("join_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="transect_id",
            separator=",",
            **(params_dict.get("join_transect_id") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=parse_transect_id)
    )

    bfill_patrol_events = (
        bfill_within_patrols.validate()
        .set_task_instance_id("bfill_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col="patrol_serial_number",
            columns=["transect_id", "num_observers"],
            skip_if_missing=True,
            **(params_dict.get("bfill_patrol_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=join_transect_id)
    )

    ffill_patrol_events = (
        ffill_within_patrols.validate()
        .set_task_instance_id("ffill_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col="patrol_serial_number",
            columns=["transect_id", "num_observers"],
            skip_if_missing=True,
            **(params_dict.get("ffill_patrol_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=bfill_patrol_events)
    )

    filter_wildlife_rep = (
        filter_row_values.validate()
        .set_task_instance_id("filter_wildlife_rep")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_type",
            values=["distancecountwildlife_rep"],
            **(params_dict.get("filter_wildlife_rep") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ffill_patrol_events)
    )

    extract_notes = (
        extract_notes_text.validate()
        .set_task_instance_id("extract_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="notes",
            new_column="other_species",
            **(params_dict.get("extract_notes") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_wildlife_rep)
    )

    zip_conn_surv_name_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_conn_surv_name_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[extract_notes, retrieve_survey_name],
            **(params_dict.get("zip_conn_surv_name_df") or {}),
        )
        .call()
    )

    add_survey_column = (
        add_constant_column.validate()
        .set_task_instance_id("add_survey_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="survey_id", **(params_dict.get("add_survey_column") or {}))
        .mapvalues(argnames=["df", "value"], argvalues=zip_conn_surv_name_df)
    )

    convert_transects_utm = (
        estimate_utm_crs.validate()
        .set_task_instance_id("convert_transects_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("convert_transects_utm") or {}))
        .mapvalues(argnames=["geodataframe"], argvalues=fetch_patrol_transects)
    )

    zip_transect_df_crs = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_transect_df_crs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[convert_transects_utm, fetch_patrol_transects],
            **(params_dict.get("zip_transect_df_crs") or {}),
        )
        .call()
    )

    reproject_transects_utm = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_transects_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("reproject_transects_utm") or {}))
        .mapvalues(argnames=["target_crs", "gdf"], argvalues=zip_transect_df_crs)
    )

    normalize_transect_names_utm = (
        format_text_column.validate()
        .set_task_instance_id("normalize_transect_names_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="name",
            method="lower",
            **(params_dict.get("normalize_transect_names_utm") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=reproject_transects_utm)
    )

    normalize_transect_underscores = (
        normalize_name_spaces.validate()
        .set_task_instance_id("normalize_transect_underscores")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="name", **(params_dict.get("normalize_transect_underscores") or {})
        )
        .mapvalues(argnames=["df"], argvalues=normalize_transect_names_utm)
    )

    zip_patrol_df_crs = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_patrol_df_crs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[convert_transects_utm, add_survey_column],
            **(params_dict.get("zip_patrol_df_crs") or {}),
        )
        .call()
    )

    patrol_events_utm = (
        reproject_gdf.validate()
        .set_task_instance_id("patrol_events_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("patrol_events_utm") or {}))
        .mapvalues(argnames=["target_crs", "gdf"], argvalues=zip_patrol_df_crs)
    )

    zip_patrol_transects = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_patrol_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[patrol_events_utm, normalize_transect_underscores],
            **(params_dict.get("zip_patrol_transects") or {}),
        )
        .call()
    )

    observers_distance = (
        add_off_transect_distance.validate()
        .set_task_instance_id("observers_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            distance_column="off_transect_dist",
            transect_id_column="transect_id",
            transect_name_column="name",
            **(params_dict.get("observers_distance") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_patrol_transects
        )
    )

    exclude_neg_off_transects = (
        filter_numeric_df.validate()
        .set_task_instance_id("exclude_neg_off_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="off_transect_dist",
            value=-1,
            reset_index=True,
            coerce_numeric=True,
            op="ne",
            **(params_dict.get("exclude_neg_off_transects") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=observers_distance)
    )

    add_orig_geom = (
        add_orig_geometry.validate()
        .set_task_instance_id("add_orig_geom")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("add_orig_geom") or {}))
        .mapvalues(argnames=["gdf"], argvalues=exclude_neg_off_transects)
    )

    estimate_animal_position = (
        estimate_animal_positions.validate()
        .set_task_instance_id("estimate_animal_position")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            distance_column="dist_to_centre",
            angle_column="radialangle",
            preserve_original_as="orig_geometry",
            **(params_dict.get("estimate_animal_position") or {}),
        )
        .mapvalues(argnames=["patrol_events"], argvalues=add_orig_geom)
    )

    zip_est_patrol_transects = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_est_patrol_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[estimate_animal_position, normalize_transect_underscores],
            **(params_dict.get("zip_est_patrol_transects") or {}),
        )
        .call()
    )

    compute_ortho_dist = (
        add_off_transect_distance.validate()
        .set_task_instance_id("compute_ortho_dist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            distance_column="ortho_dist",
            transect_id_column="transect_id",
            transect_name_column="name",
            **(params_dict.get("compute_ortho_dist") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_est_patrol_transects
        )
    )

    exclude_neg_ortho_dist = (
        filter_numeric_df.validate()
        .set_task_instance_id("exclude_neg_ortho_dist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="ortho_dist",
            value=-1,
            reset_index=True,
            coerce_numeric=True,
            op="ne",
            **(params_dict.get("exclude_neg_ortho_dist") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=compute_ortho_dist)
    )

    merge_transects = (
        merge_transect_lines.validate()
        .set_task_instance_id("merge_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("merge_transects") or {}))
        .mapvalues(argnames=["transects"], argvalues=normalize_transect_underscores)
    )

    simplify_tolerance = (
        simplify_transects.validate()
        .set_task_instance_id("simplify_tolerance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(tolerance=50, **(params_dict.get("simplify_tolerance") or {}))
        .mapvalues(argnames=["transects"], argvalues=merge_transects)
    )

    buffer_transect_segments = (
        buffer_transects.validate()
        .set_task_instance_id("buffer_transect_segments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            cap_style="flat",
            single_sided=False,
            resolution=5,
            distance=500,
            **(params_dict.get("buffer_transect_segments") or {}),
        )
        .mapvalues(argnames=["transects"], argvalues=simplify_tolerance)
    )

    zip_events_buff_trans = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_events_buff_trans")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[exclude_neg_ortho_dist, buffer_transect_segments],
            **(params_dict.get("zip_events_buff_trans") or {}),
        )
        .call()
    )

    filter_intersecting_events = (
        flag_events_intersecting_transect.validate()
        .set_task_instance_id("filter_intersecting_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            intersects_column="intersects_transect",
            transect_id_column="transect_id",
            transect_name_column="name",
            index_column="id",
            **(params_dict.get("filter_intersecting_events") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_events_buff_trans
        )
    )

    zip_filtered_events_trans = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_filtered_events_trans")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[filter_intersecting_events, buffer_transect_segments],
            **(params_dict.get("zip_filtered_events_trans") or {}),
        )
        .call()
    )

    visited_transects = (
        filter_visited_transects.validate()
        .set_task_instance_id("visited_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            intersects_column="intersects_transect",
            transect_id_column="transect_id",
            transect_name_column="name",
            **(params_dict.get("visited_transects") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_filtered_events_trans
        )
    )

    reproject_transects = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            target_crs="epsg:4326", **(params_dict.get("reproject_transects") or {})
        )
        .mapvalues(argnames=["gdf"], argvalues=visited_transects)
    )

    get_since_conf_filter = (
        get_since_filter.validate()
        .set_task_instance_id("get_since_conf_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("get_since_conf_filter") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
    )

    zip_df_since = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_df_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[get_since_conf_filter, reproject_transects],
            **(params_dict.get("zip_df_since") or {}),
        )
        .call()
    )

    add_since_transects = (
        add_constant_column.validate()
        .set_task_instance_id("add_since_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="survey_date", **(params_dict.get("add_since_transects") or {}))
        .mapvalues(argnames=["value", "df"], argvalues=zip_df_since)
    )

    convert_trans_ee = (
        to_ee_feature_collection.validate()
        .set_task_instance_id("convert_trans_ee")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=gee_client, **(params_dict.get("convert_trans_ee") or {}))
        .mapvalues(argnames=["gdf"], argvalues=add_since_transects)
    )

    zip_aoi_since = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_aoi_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[convert_trans_ee, get_since_conf_filter],
            **(params_dict.get("zip_aoi_since") or {}),
        )
        .call()
    )

    hls_ndvi_image = (
        build_hls_ndvi_image.validate()
        .set_task_instance_id("hls_ndvi_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            ndvi_window_days=None,
            max_cloud_cover=30,
            ndvi_band_name="NDVI_HSL",
            **(params_dict.get("hls_ndvi_image") or {}),
        )
        .mapvalues(argnames=["aoi", "since"], argvalues=zip_aoi_since)
    )

    create_slope_image = (
        build_slope_image.validate()
        .set_task_instance_id("create_slope_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            dem_asset="USGS/SRTMGL1_003",
            **(params_dict.get("create_slope_image") or {}),
        )
        .call()
    )

    label_ndvi_hsl = (
        label_features_with_image_stat.validate()
        .set_task_instance_id("label_ndvi_hsl")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            image=create_slope_image,
            out_column="NDVI_HSL",
            region_reducer=None,
            scale=30.0,
            reducer_key="mean",
            **(params_dict.get("label_ndvi_hsl") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=add_since_transects)
    )

    zip_df_ndvi = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_df_ndvi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[get_since_conf_filter, label_ndvi_hsl],
            **(params_dict.get("zip_df_ndvi") or {}),
        )
        .call()
    )

    add_img_date_hsl_ndvi = (
        add_constant_column.validate()
        .set_task_instance_id("add_img_date_hsl_ndvi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="img_date_hsl_ndvi",
            **(params_dict.get("add_img_date_hsl_ndvi") or {}),
        )
        .mapvalues(argnames=["value", "df"], argvalues=zip_df_ndvi)
    )

    label_slope = (
        label_features_with_image_stat.validate()
        .set_task_instance_id("label_slope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            image=create_slope_image,
            out_column="slope",
            region_reducer=None,
            scale=30.0,
            reducer_key="mean",
            **(params_dict.get("label_slope") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=add_img_date_hsl_ndvi)
    )

    filter_transect_columns = (
        select_columns.validate()
        .set_task_instance_id("filter_transect_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["name", "img_date_hsl_ndvi", "NDVI_HSL", "slope", "geometry"],
            raise_on_missing=True,
            **(params_dict.get("filter_transect_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=label_slope)
    )

    exclude_geom = (
        select_columns.validate()
        .set_task_instance_id("exclude_geom")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["name", "img_date_hsl_ndvi", "NDVI_HSL", "slope"],
            raise_on_missing=True,
            **(params_dict.get("exclude_geom") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_transect_columns)
    )

    zip_patrol_transects_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_patrol_transects_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[filter_intersecting_events, exclude_geom],
            **(params_dict.get("zip_patrol_transects_df") or {}),
        )
        .call()
    )

    merge_filtered_patrols = (
        merge_two_dataframes.validate()
        .set_task_instance_id("merge_filtered_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_on="transect_id",
            right_on="name",
            how="left",
            left_index=False,
            right_index=False,
            fillna_value=None,
            on=None,
            **(params_dict.get("merge_filtered_patrols") or {}),
        )
        .mapvalues(argnames=["left", "right"], argvalues=zip_patrol_transects_df)
    )

    select_patrol_event_cols = (
        select_columns.validate()
        .set_task_instance_id("select_patrol_event_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=[
                "transect_id",
                "level_1",
                "title",
                "patrol_id",
                "patrol_serial_number",
                "totalcount",
                "num_juveniles",
                "event_type",
                "num_observers",
                "dist_to_centre",
                "geometry",
                "species",
                "other_species",
                "time",
                "serial_number",
                "radialangle",
                "survey_id",
                "off_transect_dist",
                "orig_geometry",
                "ortho_dist",
                "intersects_transect",
                "img_date_hsl_ndvi",
                "NDVI_HSL",
                "slope",
            ],
            raise_on_missing=False,
            **(params_dict.get("select_patrol_event_cols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=merge_filtered_patrols)
    )

    combine_patrol_event_names = (
        combine_names.validate()
        .set_task_instance_id("combine_patrol_event_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            b="_analysis_data", **(params_dict.get("combine_patrol_event_names") or {})
        )
        .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
    )

    zip_filename_patrol_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_filename_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_patrol_event_names, select_patrol_event_cols],
            **(params_dict.get("zip_filename_patrol_df") or {}),
        )
        .call()
    )

    persist_patrol_events_csv = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_patrol_events_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["csv"],
            filename=None,
            sanitize=False,
            **(params_dict.get("persist_patrol_events_csv") or {}),
        )
        .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_patrol_df)
    )

    select_gpkg_columns = (
        select_columns.validate()
        .set_task_instance_id("select_gpkg_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=[
                "serial_number",
                "transect_id",
                "dist_to_centre",
                "ortho_dist",
                "intersects_transect",
                "geometry",
            ],
            raise_on_missing=False,
            **(params_dict.get("select_gpkg_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=select_patrol_event_cols)
    )

    combine_gpkg_name = (
        combine_names.validate()
        .set_task_instance_id("combine_gpkg_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(b="_events", **(params_dict.get("combine_gpkg_name") or {}))
        .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
    )

    zip_filename_gpkg_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_filename_gpkg_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_gpkg_name, select_gpkg_columns],
            **(params_dict.get("zip_filename_gpkg_df") or {}),
        )
        .call()
    )

    persist_patrol_events_gpkg = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_patrol_events_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["gpkg"],
            filename=None,
            sanitize=False,
            **(params_dict.get("persist_patrol_events_gpkg") or {}),
        )
        .mapvalues(argnames=["filename_prefix", "df"], argvalues=zip_filename_gpkg_df)
    )

    format_transect_names = (
        format_text_column.validate()
        .set_task_instance_id("format_transect_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="name",
            method="lower",
            **(params_dict.get("format_transect_names") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_transect_columns)
    )

    combine_transect_gpkg_name = (
        combine_names.validate()
        .set_task_instance_id("combine_transect_gpkg_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            b="_transects", **(params_dict.get("combine_transect_gpkg_name") or {})
        )
        .mapvalues(argnames=["a"], argvalues=retrieve_survey_name)
    )

    zip_filename_transect_df = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_filename_transect_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_transect_gpkg_name, format_transect_names],
            **(params_dict.get("zip_filename_transect_df") or {}),
        )
        .call()
    )

    persist_transects_gpkg = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_transects_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetypes=["gpkg"],
            filename=None,
            sanitize=False,
            **(params_dict.get("persist_transects_gpkg") or {}),
        )
        .mapvalues(
            argnames=["filename_prefix", "df"], argvalues=zip_filename_transect_df
        )
    )

    overall_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("overall_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("overall_dashboard") or {}),
        )
        .call()
    )

    return overall_dashboard
