# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    create_connection_configs as create_connection_configs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    split_connection_configs as split_connection_configs,
)

fetch_patrol_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_distance_sample_counts.tasks",  # 🧪
    func_name="fetch_patrol_events",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    set_dataframe_index as set_dataframe_index,
)

fetch_transects = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_distance_sample_counts.tasks",  # 🧪
    func_name="fetch_transects",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_server_name as get_server_name,
)
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

fetch_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_distance_sample_counts.tasks",  # 🧪
    func_name="fetch_events",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    join_list_column as join_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    parse_df_point as parse_df_point,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_big_life.tasks import filter_numeric_df as filter_numeric_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_constant_column as add_constant_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_off_transect_distance as add_off_transect_distance,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_orig_geometry as add_orig_geometry,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    bfill_within_patrols as bfill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    buffer_transects as buffer_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    build_hls_ndvi_image as build_hls_ndvi_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    build_slope_image as build_slope_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    combine_names as combine_names,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_field_effort as compute_field_effort,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    convert_column_timezone as convert_column_timezone,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    drop_null_columns as drop_null_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    estimate_animal_positions as estimate_animal_positions,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    estimate_utm_crs as estimate_utm_crs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    ffill_within_patrols as ffill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    filter_visited_transects as filter_visited_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    flag_events_intersecting_transect as flag_events_intersecting_transect,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_since_filter as get_since_filter,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    get_survey_name as get_survey_name,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    label_features_with_image_stat as label_features_with_image_stat,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    merge_transect_lines as merge_transect_lines,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    parse_list_column as parse_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    simplify_transects as simplify_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    to_ee_feature_collection as to_ee_feature_collection,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "gee_client": [],
        "connection_config": [],
        "split_connection_config": ["connection_config"],
        "retrieve_patrol_events": ["split_connection_config"],
        "set_patrol_index": ["retrieve_patrol_events"],
        "fetch_patrol_transects": ["split_connection_config"],
        "fetch_earthranger_client": ["split_connection_config"],
        "zip_conn_patrol_events": ["split_connection_config", "set_patrol_index"],
        "fetch_events_from_ids": ["zip_conn_patrol_events"],
        "filter_survey_events": ["fetch_events_from_ids"],
        "extract_lat_long": ["filter_survey_events"],
        "normalize_reported_by": ["extract_lat_long"],
        "extract_reported_by": ["normalize_reported_by"],
        "zip_conn_survey_df": ["extract_reported_by", "fetch_earthranger_client"],
        "process_survey_event_details": ["zip_conn_survey_df"],
        "normalize_survey_df": ["process_survey_event_details"],
        "map_survey_event_columns": ["normalize_survey_df"],
        "parse_team_members": ["map_survey_event_columns"],
        "join_team_members": ["parse_team_members"],
        "drop_null_cols": ["join_team_members"],
        "retrieve_survey_name": ["split_connection_config"],
        "combine_survey_event_names": ["retrieve_survey_name"],
        "zip_filename_survey_df": ["combine_survey_event_names", "drop_null_cols"],
        "persist_survey_event_metadata": ["zip_filename_survey_df"],
        "zip_connection_metadata": ["split_connection_config", "drop_null_cols"],
        "field_effort": ["zip_connection_metadata"],
        "combine_survey_field": ["retrieve_survey_name"],
        "zip_filename_fe": ["combine_survey_field", "field_effort"],
        "persist_field_effort": ["zip_filename_fe"],
        "select_event_details": ["fetch_events_from_ids"],
        "zip_patrol_events_df": ["set_patrol_index", "select_event_details"],
        "merge_patrol_events": ["zip_patrol_events_df"],
        "convert_tz_utc": ["time_range", "merge_patrol_events"],
        "normalize_event_details": ["convert_tz_utc"],
        "map_patrol_df": ["normalize_event_details"],
        "normalize_transect_id": ["map_patrol_df"],
        "parse_transect_id": ["normalize_transect_id"],
        "join_transect_id": ["parse_transect_id"],
        "bfill_patrol_events": ["join_transect_id"],
        "ffill_patrol_events": ["bfill_patrol_events"],
        "filter_wildlife_rep": ["ffill_patrol_events"],
        "zip_conn_surv_name_df": ["filter_wildlife_rep", "retrieve_survey_name"],
        "add_survey_column": ["zip_conn_surv_name_df"],
        "convert_transects_utm": ["fetch_patrol_transects"],
        "zip_transect_df_crs": ["convert_transects_utm", "fetch_patrol_transects"],
        "reproject_transects_utm": ["zip_transect_df_crs"],
        "zip_patrol_df_crs": ["convert_transects_utm", "add_survey_column"],
        "patrol_events_utm": ["zip_patrol_df_crs"],
        "zip_patrol_transects": ["patrol_events_utm", "reproject_transects_utm"],
        "observers_distance": ["zip_patrol_transects"],
        "exclude_neg_off_transects": ["observers_distance"],
        "add_orig_geom": ["exclude_neg_off_transects"],
        "estimate_animal_position": ["add_orig_geom"],
        "zip_est_patrol_transects": [
            "estimate_animal_position",
            "reproject_transects_utm",
        ],
        "compute_ortho_dist": ["zip_est_patrol_transects"],
        "exclude_neg_ortho_dist": ["compute_ortho_dist"],
        "merge_transects": ["reproject_transects_utm"],
        "simplify_tolerance": ["merge_transects"],
        "buffer_transect_segments": ["simplify_tolerance"],
        "zip_events_buff_trans": ["exclude_neg_ortho_dist", "buffer_transect_segments"],
        "filter_intersecting_events": ["zip_events_buff_trans"],
        "zip_filtered_events_trans": [
            "filter_intersecting_events",
            "buffer_transect_segments",
        ],
        "visited_transects": ["zip_filtered_events_trans"],
        "reproject_transects": ["visited_transects"],
        "get_since_conf_filter": ["split_connection_config"],
        "zip_df_since": ["get_since_conf_filter", "reproject_transects"],
        "add_since_transects": ["zip_df_since"],
        "convert_trans_ee": ["gee_client", "add_since_transects"],
        "zip_aoi_since": ["convert_trans_ee", "get_since_conf_filter"],
        "hls_ndvi_image": ["gee_client", "zip_aoi_since"],
        "create_slope_image": ["gee_client"],
        "label_ndvi_hsl": ["create_slope_image", "add_since_transects"],
        "zip_df_ndvi": ["get_since_conf_filter", "label_ndvi_hsl"],
        "add_img_date_hsl_ndvi": ["zip_df_ndvi"],
        "label_slope": ["create_slope_image", "add_img_date_hsl_ndvi"],
        "filter_transect_columns": ["label_slope"],
        "exclude_geom": ["filter_transect_columns"],
        "zip_patrol_transects_df": ["filter_intersecting_events", "exclude_geom"],
        "merge_filtered_patrols": ["zip_patrol_transects_df"],
        "select_patrol_event_cols": ["merge_filtered_patrols"],
        "combine_patrol_event_names": ["retrieve_survey_name"],
        "zip_filename_patrol_df": [
            "combine_patrol_event_names",
            "select_patrol_event_cols",
        ],
        "persist_patrol_events_csv": ["zip_filename_patrol_df"],
        "select_gpkg_columns": ["select_patrol_event_cols"],
        "combine_gpkg_name": ["retrieve_survey_name"],
        "zip_filename_gpkg_df": ["combine_gpkg_name", "select_gpkg_columns"],
        "persist_patrol_events_gpkg": ["zip_filename_gpkg_df"],
        "combine_transect_gpkg_name": ["retrieve_survey_name"],
        "zip_filename_transect_df": [
            "combine_transect_gpkg_name",
            "filter_transect_columns",
        ],
        "persist_transects_gpkg": ["zip_filename_transect_df"],
        "combine_orig_transect_gpkg_name": ["retrieve_survey_name"],
        "zip_filename_orig_transect_df": [
            "combine_orig_transect_gpkg_name",
            "reproject_transects",
        ],
        "persist_orig_transects_gpkg": ["zip_filename_orig_transect_df"],
        "overall_dashboard": ["workflow_details", "time_range", "groupers"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "gee_client": Node(
            async_task=set_gee_connection.validate()
            .set_task_instance_id("gee_client")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("gee_client") or {}),
            method="call",
        ),
        "connection_config": Node(
            async_task=create_connection_configs.validate()
            .set_task_instance_id("connection_config")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("connection_config") or {}),
            method="call",
        ),
        "split_connection_config": Node(
            async_task=split_connection_configs.validate()
            .set_task_instance_id("split_connection_config")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "connection_configs": DependsOn("connection_config"),
            }
            | (params_dict.get("split_connection_config") or {}),
            method="call",
        ),
        "retrieve_patrol_events": Node(
            async_task=fetch_patrol_events.validate()
            .set_task_instance_id("retrieve_patrol_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("retrieve_patrol_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey"],
                "argvalues": DependsOn("split_connection_config"),
            },
        ),
        "set_patrol_index": Node(
            async_task=set_dataframe_index.validate()
            .set_task_instance_id("set_patrol_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "id",
            }
            | (params_dict.get("set_patrol_index") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("retrieve_patrol_events"),
            },
        ),
        "fetch_patrol_transects": Node(
            async_task=fetch_transects.validate()
            .set_task_instance_id("fetch_patrol_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("fetch_patrol_transects") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey"],
                "argvalues": DependsOn("split_connection_config"),
            },
        ),
        "fetch_earthranger_client": Node(
            async_task=get_server_name.validate()
            .set_task_instance_id("fetch_earthranger_client")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("fetch_earthranger_client") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey"],
                "argvalues": DependsOn("split_connection_config"),
            },
        ),
        "zip_conn_patrol_events": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_conn_patrol_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("split_connection_config"),
                    DependsOn("set_patrol_index"),
                ],
            }
            | (params_dict.get("zip_conn_patrol_events") or {}),
            method="call",
        ),
        "fetch_events_from_ids": Node(
            async_task=fetch_events.validate()
            .set_task_instance_id("fetch_events_from_ids")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "chunk_size": 50,
            }
            | (params_dict.get("fetch_events_from_ids") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey", "patrol_events"],
                "argvalues": DependsOn("zip_conn_patrol_events"),
            },
        ),
        "filter_survey_events": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("filter_survey_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_type",
                "values": [
                    "distancecountpatrol_rep",
                    "distance_count_patrol_metadata",
                ],
            }
            | (params_dict.get("filter_survey_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("fetch_events_from_ids"),
            },
        ),
        "extract_lat_long": Node(
            async_task=parse_df_point.validate()
            .set_task_instance_id("extract_lat_long")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("extract_lat_long") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("filter_survey_events"),
            },
        ),
        "normalize_reported_by": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_reported_by")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "reported_by",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_reported_by") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("extract_lat_long"),
            },
        ),
        "extract_reported_by": Node(
            async_task=join_list_column.validate()
            .set_task_instance_id("extract_reported_by")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "reported_by__name",
                "separator": ",",
            }
            | (params_dict.get("extract_reported_by") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("normalize_reported_by"),
            },
        ),
        "zip_conn_survey_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_conn_survey_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("extract_reported_by"),
                    DependsOn("fetch_earthranger_client"),
                ],
            }
            | (params_dict.get("zip_conn_survey_df") or {}),
            method="call",
        ),
        "process_survey_event_details": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_survey_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_survey_event_details") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df", "client"],
                "argvalues": DependsOn("zip_conn_survey_df"),
            },
        ),
        "normalize_survey_df": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_survey_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_survey_df") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("process_survey_event_details"),
            },
        ),
        "map_survey_event_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_survey_event_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": False,
                "drop_columns": [
                    "id",
                ],
                "retain_columns": [
                    "serial_number",
                    "event_type",
                    "time",
                    "Latitude",
                    "Longitude",
                    "reported_by__name",
                    "event_details__Transect ID",
                    "event_details__Transect_ID",
                    "event_details__Team_members",
                    "event_details__Team Members",
                    "event_details__Number_of_observers",
                    "event_details__Number of Observers",
                ],
                "rename_columns": {
                    "time": "time",
                    "event_type": "event_type",
                    "title": "title",
                    "geometry": "geometry",
                    "serial_number": "serial_number",
                    "patrol_id": "patrol_id",
                    "patrol_serial_number": "patrol_serial_number",
                    "reported_by__name": "reported_by",
                    "Latitude": "latitude",
                    "Longitude": "longitude",
                    "event_details__Number_of_observers": "Number of Observers",
                    "event_details__Team_members": "Team Members",
                    "event_details__Transect_ID": "Transect ID",
                    "event_details__Number of Observers": "Number of Observers",
                    "event_details__Team Members": "Team Members",
                    "event_details__Transect ID": "Transect ID",
                },
            }
            | (params_dict.get("map_survey_event_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("normalize_survey_df"),
            },
        ),
        "parse_team_members": Node(
            async_task=parse_list_column.validate()
            .set_task_instance_id("parse_team_members")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "Team Members",
            }
            | (params_dict.get("parse_team_members") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("map_survey_event_columns"),
            },
        ),
        "join_team_members": Node(
            async_task=join_list_column.validate()
            .set_task_instance_id("join_team_members")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "Team Members",
                "separator": ",",
            }
            | (params_dict.get("join_team_members") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("parse_team_members"),
            },
        ),
        "drop_null_cols": Node(
            async_task=drop_null_columns.validate()
            .set_task_instance_id("drop_null_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("drop_null_cols") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("join_team_members"),
            },
        ),
        "retrieve_survey_name": Node(
            async_task=get_survey_name.validate()
            .set_task_instance_id("retrieve_survey_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("retrieve_survey_name") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey"],
                "argvalues": DependsOn("split_connection_config"),
            },
        ),
        "combine_survey_event_names": Node(
            async_task=combine_names.validate()
            .set_task_instance_id("combine_survey_event_names")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "b": "_analysis_metadata",
            }
            | (params_dict.get("combine_survey_event_names") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["a"],
                "argvalues": DependsOn("retrieve_survey_name"),
            },
        ),
        "zip_filename_survey_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filename_survey_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("combine_survey_event_names"),
                    DependsOn("drop_null_cols"),
                ],
            }
            | (params_dict.get("zip_filename_survey_df") or {}),
            method="call",
        ),
        "persist_survey_event_metadata": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_survey_event_metadata")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetypes": [
                    "csv",
                ],
                "filename": None,
                "sanitize": False,
            }
            | (params_dict.get("persist_survey_event_metadata") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["filename_prefix", "df"],
                "argvalues": DependsOn("zip_filename_survey_df"),
            },
        ),
        "zip_connection_metadata": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_connection_metadata")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("split_connection_config"),
                    DependsOn("drop_null_cols"),
                ],
            }
            | (params_dict.get("zip_connection_metadata") or {}),
            method="call",
        ),
        "field_effort": Node(
            async_task=compute_field_effort.validate()
            .set_task_instance_id("field_effort")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("field_effort") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey", "df"],
                "argvalues": DependsOn("zip_connection_metadata"),
            },
        ),
        "combine_survey_field": Node(
            async_task=combine_names.validate()
            .set_task_instance_id("combine_survey_field")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "b": "_field_effort",
            }
            | (params_dict.get("combine_survey_field") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["a"],
                "argvalues": DependsOn("retrieve_survey_name"),
            },
        ),
        "zip_filename_fe": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filename_fe")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("combine_survey_field"),
                    DependsOn("field_effort"),
                ],
            }
            | (params_dict.get("zip_filename_fe") or {}),
            method="call",
        ),
        "persist_field_effort": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_field_effort")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetypes": [
                    "csv",
                ],
                "filename": None,
                "sanitize": False,
            }
            | (params_dict.get("persist_field_effort") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["filename_prefix", "df"],
                "argvalues": DependsOn("zip_filename_fe"),
            },
        ),
        "select_event_details": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("select_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "event_details",
                ],
                "raise_on_missing": False,
            }
            | (params_dict.get("select_event_details") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("fetch_events_from_ids"),
            },
        ),
        "zip_patrol_events_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_patrol_events_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("set_patrol_index"),
                    DependsOn("select_event_details"),
                ],
            }
            | (params_dict.get("zip_patrol_events_df") or {}),
            method="call",
        ),
        "merge_patrol_events": Node(
            async_task=merge_two_dataframes.validate()
            .set_task_instance_id("merge_patrol_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "how": "left",
                "left_on": None,
                "right_on": None,
                "left_index": True,
                "right_index": True,
                "fillna_value": None,
                "on": None,
            }
            | (params_dict.get("merge_patrol_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["left", "right"],
                "argvalues": DependsOn("zip_patrol_events_df"),
            },
        ),
        "convert_tz_utc": Node(
            async_task=convert_column_timezone.validate()
            .set_task_instance_id("convert_tz_utc")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "time",
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("convert_tz_utc") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("merge_patrol_events"),
            },
        ),
        "normalize_event_details": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_event_details") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("convert_tz_utc"),
            },
        ),
        "map_patrol_df": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_patrol_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "drop_columns": None,
                "raise_if_not_found": False,
                "retain_columns": None,
                "rename_columns": {
                    "event_details__distancecountpatrol_numberofobservers": "num_observers",
                    "event_details__distancecountpatrol_teammembers": "Team Members",
                    "event_details__distancecountpatrol_transectid": "transect_id",
                    "event_details__distancecountwildlife_distancetocentre": "dist_to_centre",
                    "event_details__distancecountwildlife_numberofjuveniles": "num_juveniles",
                    "event_details__distancecountwildlife_radialangle": "radialangle",
                    "event_details__distancecountwildlife_species": "species",
                    "event_details__distancecountwildlife_totalcount": "totalcount",
                    "event_details__Transect_ID": "transect_id_v2",
                    "event_details__Team_members": "Team Members",
                    "event_details__Number_of_observers": "num_observers",
                    "event_details__Number_of_Observers": "num_observers",
                    "event_details__Number of Observers": "num_observers",
                },
            }
            | (params_dict.get("map_patrol_df") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("normalize_event_details"),
            },
        ),
        "normalize_transect_id": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("normalize_transect_id")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": False,
                "rename_columns": {
                    "transect_id_v2": "transect_id",
                },
            }
            | (params_dict.get("normalize_transect_id") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("map_patrol_df"),
            },
        ),
        "parse_transect_id": Node(
            async_task=parse_list_column.validate()
            .set_task_instance_id("parse_transect_id")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "transect_id",
            }
            | (params_dict.get("parse_transect_id") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("normalize_transect_id"),
            },
        ),
        "join_transect_id": Node(
            async_task=join_list_column.validate()
            .set_task_instance_id("join_transect_id")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "transect_id",
                "separator": ",",
            }
            | (params_dict.get("join_transect_id") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("parse_transect_id"),
            },
        ),
        "bfill_patrol_events": Node(
            async_task=bfill_within_patrols.validate()
            .set_task_instance_id("bfill_patrol_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "group_col": "patrol_serial_number",
                "columns": [
                    "transect_id",
                    "num_observers",
                ],
                "skip_if_missing": True,
            }
            | (params_dict.get("bfill_patrol_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("join_transect_id"),
            },
        ),
        "ffill_patrol_events": Node(
            async_task=ffill_within_patrols.validate()
            .set_task_instance_id("ffill_patrol_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "group_col": "patrol_serial_number",
                "columns": [
                    "transect_id",
                    "num_observers",
                ],
                "skip_if_missing": True,
            }
            | (params_dict.get("ffill_patrol_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("bfill_patrol_events"),
            },
        ),
        "filter_wildlife_rep": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("filter_wildlife_rep")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_type",
                "values": [
                    "distancecountwildlife_rep",
                ],
            }
            | (params_dict.get("filter_wildlife_rep") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("ffill_patrol_events"),
            },
        ),
        "zip_conn_surv_name_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_conn_surv_name_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("filter_wildlife_rep"),
                    DependsOn("retrieve_survey_name"),
                ],
            }
            | (params_dict.get("zip_conn_surv_name_df") or {}),
            method="call",
        ),
        "add_survey_column": Node(
            async_task=add_constant_column.validate()
            .set_task_instance_id("add_survey_column")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "survey_id",
            }
            | (params_dict.get("add_survey_column") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df", "value"],
                "argvalues": DependsOn("zip_conn_surv_name_df"),
            },
        ),
        "convert_transects_utm": Node(
            async_task=estimate_utm_crs.validate()
            .set_task_instance_id("convert_transects_utm")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("convert_transects_utm") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("fetch_patrol_transects"),
            },
        ),
        "zip_transect_df_crs": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_transect_df_crs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("convert_transects_utm"),
                    DependsOn("fetch_patrol_transects"),
                ],
            }
            | (params_dict.get("zip_transect_df_crs") or {}),
            method="call",
        ),
        "reproject_transects_utm": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_transects_utm")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("reproject_transects_utm") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["target_crs", "gdf"],
                "argvalues": DependsOn("zip_transect_df_crs"),
            },
        ),
        "zip_patrol_df_crs": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_patrol_df_crs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("convert_transects_utm"),
                    DependsOn("add_survey_column"),
                ],
            }
            | (params_dict.get("zip_patrol_df_crs") or {}),
            method="call",
        ),
        "patrol_events_utm": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("patrol_events_utm")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("patrol_events_utm") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["target_crs", "gdf"],
                "argvalues": DependsOn("zip_patrol_df_crs"),
            },
        ),
        "zip_patrol_transects": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_patrol_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("patrol_events_utm"),
                    DependsOn("reproject_transects_utm"),
                ],
            }
            | (params_dict.get("zip_patrol_transects") or {}),
            method="call",
        ),
        "observers_distance": Node(
            async_task=add_off_transect_distance.validate()
            .set_task_instance_id("observers_distance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "distance_column": "off_transect_dist",
                "transect_id_column": "transect_id",
                "transect_name_column": "name",
            }
            | (params_dict.get("observers_distance") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["patrol_events", "transects"],
                "argvalues": DependsOn("zip_patrol_transects"),
            },
        ),
        "exclude_neg_off_transects": Node(
            async_task=filter_numeric_df.validate()
            .set_task_instance_id("exclude_neg_off_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "off_transect_dist",
                "value": -1,
                "reset_index": True,
                "coerce_numeric": True,
                "op": "ne",
            }
            | (params_dict.get("exclude_neg_off_transects") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("observers_distance"),
            },
        ),
        "add_orig_geom": Node(
            async_task=add_orig_geometry.validate()
            .set_task_instance_id("add_orig_geom")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("add_orig_geom") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("exclude_neg_off_transects"),
            },
        ),
        "estimate_animal_position": Node(
            async_task=estimate_animal_positions.validate()
            .set_task_instance_id("estimate_animal_position")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "distance_column": "dist_to_centre",
                "angle_column": "radialangle",
                "preserve_original_as": "orig_geometry",
            }
            | (params_dict.get("estimate_animal_position") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["patrol_events"],
                "argvalues": DependsOn("add_orig_geom"),
            },
        ),
        "zip_est_patrol_transects": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_est_patrol_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("estimate_animal_position"),
                    DependsOn("reproject_transects_utm"),
                ],
            }
            | (params_dict.get("zip_est_patrol_transects") or {}),
            method="call",
        ),
        "compute_ortho_dist": Node(
            async_task=add_off_transect_distance.validate()
            .set_task_instance_id("compute_ortho_dist")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "distance_column": "ortho_dist",
                "transect_id_column": "transect_id",
                "transect_name_column": "name",
            }
            | (params_dict.get("compute_ortho_dist") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["patrol_events", "transects"],
                "argvalues": DependsOn("zip_est_patrol_transects"),
            },
        ),
        "exclude_neg_ortho_dist": Node(
            async_task=filter_numeric_df.validate()
            .set_task_instance_id("exclude_neg_ortho_dist")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "ortho_dist",
                "value": -1,
                "reset_index": True,
                "coerce_numeric": True,
                "op": "ne",
            }
            | (params_dict.get("exclude_neg_ortho_dist") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("compute_ortho_dist"),
            },
        ),
        "merge_transects": Node(
            async_task=merge_transect_lines.validate()
            .set_task_instance_id("merge_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("merge_transects") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["transects"],
                "argvalues": DependsOn("reproject_transects_utm"),
            },
        ),
        "simplify_tolerance": Node(
            async_task=simplify_transects.validate()
            .set_task_instance_id("simplify_tolerance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tolerance": 50,
            }
            | (params_dict.get("simplify_tolerance") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["transects"],
                "argvalues": DependsOn("merge_transects"),
            },
        ),
        "buffer_transect_segments": Node(
            async_task=buffer_transects.validate()
            .set_task_instance_id("buffer_transect_segments")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "cap_style": "flat",
                "single_sided": False,
                "resolution": 5,
                "distance": 500,
            }
            | (params_dict.get("buffer_transect_segments") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["transects"],
                "argvalues": DependsOn("simplify_tolerance"),
            },
        ),
        "zip_events_buff_trans": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_events_buff_trans")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("exclude_neg_ortho_dist"),
                    DependsOn("buffer_transect_segments"),
                ],
            }
            | (params_dict.get("zip_events_buff_trans") or {}),
            method="call",
        ),
        "filter_intersecting_events": Node(
            async_task=flag_events_intersecting_transect.validate()
            .set_task_instance_id("filter_intersecting_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "intersects_column": "intersects_transect",
                "transect_id_column": "transect_id",
                "transect_name_column": "name",
                "index_column": "id",
            }
            | (params_dict.get("filter_intersecting_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["patrol_events", "transects"],
                "argvalues": DependsOn("zip_events_buff_trans"),
            },
        ),
        "zip_filtered_events_trans": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filtered_events_trans")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("filter_intersecting_events"),
                    DependsOn("buffer_transect_segments"),
                ],
            }
            | (params_dict.get("zip_filtered_events_trans") or {}),
            method="call",
        ),
        "visited_transects": Node(
            async_task=filter_visited_transects.validate()
            .set_task_instance_id("visited_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "intersects_column": "intersects_transect",
                "transect_id_column": "transect_id",
                "transect_name_column": "name",
            }
            | (params_dict.get("visited_transects") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["patrol_events", "transects"],
                "argvalues": DependsOn("zip_filtered_events_trans"),
            },
        ),
        "reproject_transects": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "target_crs": "epsg:4326",
            }
            | (params_dict.get("reproject_transects") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("visited_transects"),
            },
        ),
        "get_since_conf_filter": Node(
            async_task=get_since_filter.validate()
            .set_task_instance_id("get_since_conf_filter")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("get_since_conf_filter") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["connection_survey"],
                "argvalues": DependsOn("split_connection_config"),
            },
        ),
        "zip_df_since": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_df_since")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("get_since_conf_filter"),
                    DependsOn("reproject_transects"),
                ],
            }
            | (params_dict.get("zip_df_since") or {}),
            method="call",
        ),
        "add_since_transects": Node(
            async_task=add_constant_column.validate()
            .set_task_instance_id("add_since_transects")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "survey_date",
            }
            | (params_dict.get("add_since_transects") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["value", "df"],
                "argvalues": DependsOn("zip_df_since"),
            },
        ),
        "convert_trans_ee": Node(
            async_task=to_ee_feature_collection.validate()
            .set_task_instance_id("convert_trans_ee")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
            }
            | (params_dict.get("convert_trans_ee") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("add_since_transects"),
            },
        ),
        "zip_aoi_since": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_aoi_since")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("convert_trans_ee"),
                    DependsOn("get_since_conf_filter"),
                ],
            }
            | (params_dict.get("zip_aoi_since") or {}),
            method="call",
        ),
        "hls_ndvi_image": Node(
            async_task=build_hls_ndvi_image.validate()
            .set_task_instance_id("hls_ndvi_image")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
                "ndvi_window_days": None,
                "max_cloud_cover": 30,
                "ndvi_band_name": "NDVI_HSL",
            }
            | (params_dict.get("hls_ndvi_image") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["aoi", "since"],
                "argvalues": DependsOn("zip_aoi_since"),
            },
        ),
        "create_slope_image": Node(
            async_task=build_slope_image.validate()
            .set_task_instance_id("create_slope_image")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
                "dem_asset": "USGS/SRTMGL1_003",
            }
            | (params_dict.get("create_slope_image") or {}),
            method="call",
        ),
        "label_ndvi_hsl": Node(
            async_task=label_features_with_image_stat.validate()
            .set_task_instance_id("label_ndvi_hsl")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "image": DependsOn("create_slope_image"),
                "out_column": "NDVI_HSL",
                "region_reducer": None,
                "scale": 30.0,
                "reducer_key": "mean",
            }
            | (params_dict.get("label_ndvi_hsl") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("add_since_transects"),
            },
        ),
        "zip_df_ndvi": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_df_ndvi")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("get_since_conf_filter"),
                    DependsOn("label_ndvi_hsl"),
                ],
            }
            | (params_dict.get("zip_df_ndvi") or {}),
            method="call",
        ),
        "add_img_date_hsl_ndvi": Node(
            async_task=add_constant_column.validate()
            .set_task_instance_id("add_img_date_hsl_ndvi")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "img_date_hsl_ndvi",
            }
            | (params_dict.get("add_img_date_hsl_ndvi") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["value", "df"],
                "argvalues": DependsOn("zip_df_ndvi"),
            },
        ),
        "label_slope": Node(
            async_task=label_features_with_image_stat.validate()
            .set_task_instance_id("label_slope")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "image": DependsOn("create_slope_image"),
                "out_column": "slope",
                "region_reducer": None,
                "scale": 30.0,
                "reducer_key": "mean",
            }
            | (params_dict.get("label_slope") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("add_img_date_hsl_ndvi"),
            },
        ),
        "filter_transect_columns": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("filter_transect_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "name",
                    "img_date_hsl_ndvi",
                    "NDVI_HSL",
                    "slope",
                    "geometry",
                ],
                "raise_on_missing": True,
            }
            | (params_dict.get("filter_transect_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("label_slope"),
            },
        ),
        "exclude_geom": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("exclude_geom")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "name",
                    "img_date_hsl_ndvi",
                    "NDVI_HSL",
                    "slope",
                ],
                "raise_on_missing": True,
            }
            | (params_dict.get("exclude_geom") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("filter_transect_columns"),
            },
        ),
        "zip_patrol_transects_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_patrol_transects_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("filter_intersecting_events"),
                    DependsOn("exclude_geom"),
                ],
            }
            | (params_dict.get("zip_patrol_transects_df") or {}),
            method="call",
        ),
        "merge_filtered_patrols": Node(
            async_task=merge_two_dataframes.validate()
            .set_task_instance_id("merge_filtered_patrols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left_on": "transect_id",
                "right_on": "name",
                "how": "left",
                "left_index": False,
                "right_index": False,
                "fillna_value": None,
                "on": None,
            }
            | (params_dict.get("merge_filtered_patrols") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["left", "right"],
                "argvalues": DependsOn("zip_patrol_transects_df"),
            },
        ),
        "select_patrol_event_cols": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("select_patrol_event_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "transect_id",
                    "level_1",
                    "title",
                    "patrol_id",
                    "patrol_serial_number",
                    "totalcount",
                    "num_juveniles",
                    "event_type",
                    "num_observers",
                    "dist_to_centre",
                    "geometry",
                    "species",
                    "time",
                    "serial_number",
                    "radialangle",
                    "survey_id",
                    "off_transect_dist",
                    "orig_geometry",
                    "ortho_dist",
                    "intersects_transect",
                    "img_date_hsl_ndvi",
                    "NDVI_HSL",
                    "slope",
                ],
                "raise_on_missing": False,
            }
            | (params_dict.get("select_patrol_event_cols") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("merge_filtered_patrols"),
            },
        ),
        "combine_patrol_event_names": Node(
            async_task=combine_names.validate()
            .set_task_instance_id("combine_patrol_event_names")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "b": "_analysis_data",
            }
            | (params_dict.get("combine_patrol_event_names") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["a"],
                "argvalues": DependsOn("retrieve_survey_name"),
            },
        ),
        "zip_filename_patrol_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filename_patrol_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("combine_patrol_event_names"),
                    DependsOn("select_patrol_event_cols"),
                ],
            }
            | (params_dict.get("zip_filename_patrol_df") or {}),
            method="call",
        ),
        "persist_patrol_events_csv": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_patrol_events_csv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetypes": [
                    "csv",
                ],
                "filename": None,
                "sanitize": False,
            }
            | (params_dict.get("persist_patrol_events_csv") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["filename_prefix", "df"],
                "argvalues": DependsOn("zip_filename_patrol_df"),
            },
        ),
        "select_gpkg_columns": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("select_gpkg_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "serial_number",
                    "transect_id",
                    "dist_to_centre",
                    "ortho_dist",
                    "intersects_transect",
                    "geometry",
                ],
                "raise_on_missing": False,
            }
            | (params_dict.get("select_gpkg_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("select_patrol_event_cols"),
            },
        ),
        "combine_gpkg_name": Node(
            async_task=combine_names.validate()
            .set_task_instance_id("combine_gpkg_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "b": "_events",
            }
            | (params_dict.get("combine_gpkg_name") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["a"],
                "argvalues": DependsOn("retrieve_survey_name"),
            },
        ),
        "zip_filename_gpkg_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filename_gpkg_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("combine_gpkg_name"),
                    DependsOn("select_gpkg_columns"),
                ],
            }
            | (params_dict.get("zip_filename_gpkg_df") or {}),
            method="call",
        ),
        "persist_patrol_events_gpkg": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_patrol_events_gpkg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetypes": [
                    "gpkg",
                ],
                "filename": None,
                "sanitize": False,
            }
            | (params_dict.get("persist_patrol_events_gpkg") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["filename_prefix", "df"],
                "argvalues": DependsOn("zip_filename_gpkg_df"),
            },
        ),
        "combine_transect_gpkg_name": Node(
            async_task=combine_names.validate()
            .set_task_instance_id("combine_transect_gpkg_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "b": "_transects",
            }
            | (params_dict.get("combine_transect_gpkg_name") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["a"],
                "argvalues": DependsOn("retrieve_survey_name"),
            },
        ),
        "zip_filename_transect_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filename_transect_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("combine_transect_gpkg_name"),
                    DependsOn("filter_transect_columns"),
                ],
            }
            | (params_dict.get("zip_filename_transect_df") or {}),
            method="call",
        ),
        "persist_transects_gpkg": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_transects_gpkg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetypes": [
                    "gpkg",
                ],
                "filename": None,
                "sanitize": False,
            }
            | (params_dict.get("persist_transects_gpkg") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["filename_prefix", "df"],
                "argvalues": DependsOn("zip_filename_transect_df"),
            },
        ),
        "combine_orig_transect_gpkg_name": Node(
            async_task=combine_names.validate()
            .set_task_instance_id("combine_orig_transect_gpkg_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "b": "_orig_transects",
            }
            | (params_dict.get("combine_orig_transect_gpkg_name") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["a"],
                "argvalues": DependsOn("retrieve_survey_name"),
            },
        ),
        "zip_filename_orig_transect_df": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_filename_orig_transect_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("combine_orig_transect_gpkg_name"),
                    DependsOn("reproject_transects"),
                ],
            }
            | (params_dict.get("zip_filename_orig_transect_df") or {}),
            method="call",
        ),
        "persist_orig_transects_gpkg": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_orig_transects_gpkg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetypes": [
                    "gpkg",
                ],
                "filename": None,
                "sanitize": False,
            }
            | (params_dict.get("persist_orig_transects_gpkg") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["filename_prefix", "df"],
                "argvalues": DependsOn("zip_filename_orig_transect_df"),
            },
        ),
        "overall_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("overall_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("overall_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
